### ISSUE TITLE
Get ERROR after send jSON input

### ISSUE THREAD

**Issue by VuDucNamvdn** [getnamo/machine-learning-remote-ue4#6]
![image](https://user-images.githubusercontent.com/43442087/82809631-be2bcf00-9eb6-11ea-985b-1a444c2839ac.png)
![image](https://user-images.githubusercontent.com/43442087/82809654-c97efa80-9eb6-11ea-9836-492b3ee1cc13.png)
I got an JSONDecodeError when i tried to send an input. It's saying I got a None when I was supposed to get a string.

**Comment by getnamo** [comment]
I believe that the current function requires a SIOJsonObject not a value. Try sending e.g. {"mystring":"a"} or composing it from structs/SIOJson and encoding to Json. Obvious enhancement here is to add support for non-object values.

**Comment by VuDucNamvdn** [comment]
![image](https://user-images.githubusercontent.com/43442087/82853274-84e37580-9f2f-11ea-9cf7-1f6b211fbb9c.png)
Thank you for the solution but I still got a Error in unreal_engine.py script say it missing argument for run_on_gt()

**Comment by getnamo** [comment]
Hmm interesting, do you know if the example scripts like https://github.com/getnamo/ml-remote-server/blob/master/scripts/add_example.py work for you or do you get the same issue?

**Comment by VuDucNamvdn** [comment]
![image](https://user-images.githubusercontent.com/43442087/83269437-4c72be80-a1f1-11ea-9504-68ae9f56cac0.png)

Sr for late respond I think I just fix the problem on mistake idk why. It now runs perfectly fine.
