### ISSUE TITLE
"The client is using an unsupported version of the Socket.IO or Engine.IO protocols"

### ISSUE THREAD

**Issue by BabaBert** [getnamo/machine-learning-remote-ue4#8]
I'm struggling to get a stable connection between the server and the client for the in the title named issue.

I assume that this specific issue is related to the version compatibility between the packages on the client and server site
https://github.com/miguelgrinberg/python-socketio/issues/578
![101471065-cb576980-3981-11eb-95b9-bc961372a6fe](https://user-images.githubusercontent.com/36105102/103365169-62ae6900-4ab7-11eb-8e7f-c951286f0eb2.png)

these are the modules I have installed on the server:
python-engineio==3.14.2
python-socketio==4.6.1
socketio==0.2.1
Flask-SocketIO==4.3.0

But I don't know how to resolve this since I don't have insight into the packages used on the client-side.
I'd appreciate any help in this regard, thanks.

**Comment by getnamo** [comment]
I believe a 1.x or 2.x should work with current socket.io client (3.x untested). Haven't seen an update to socket.io c++ client in a while, might need to take a look to see if we can't bring 3.x to the base libraries (https://github.com/getnamo/socketio-client-ue4/tree/master/Source/SocketIOLib/Private)

**Comment by getnamo** [comment]
https://github.com/getnamo/ml-remote-server/blob/master/requirements.txt these are the reqs the server uses atm
